# Generated by Django 3.2.5 on 2021-07-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('locations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.locations')),
                ('ProductId', models.CharField(max_length=100)),
                ('qt', models.IntegerField()),
            ],
            bases=('home.locations',),
        ),
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.product')),
                ('movementId', models.CharField(max_length=50)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('from_location', models.CharField(blank=True, max_length=50)),
                ('to_location', models.CharField(blank=True, max_length=50)),
                ('qty', models.IntegerField()),
            ],
            bases=('home.product',),
        ),
    ]
